const axios = require('axios');
const Queue = require('../../../../utils/queue');

class GradingMill {
  constructor() {
    this.credentials = {
      email: process.env.MILL_EMAIL || 'j',
      password: process.env.MILL_PASSWORD || 'j',
    };
    this.baseUrl =
      process.env.MILL_API_URL || 'https://management.srs-ssms.com/api';
    this.queue = global.queue;
  }

  async getMillData(sock) {
    try {
      const response = await axios.get(`${this.baseUrl}/getdatamilljobs`, {
        params: this.credentials,
      });

      const { data, id_jobs, pdf_name, image_name } = response.data;

      if (!data || data.length === 0) {
        global.queue.emitLog('No mill data available to process', 'info');
        return;
      }

      for (const itemdata of data) {
        const message = this.formatGradingMessage(itemdata);
        const targetGroup = this.getTargetGroup(itemdata.mill);

        if (!targetGroup) {
          global.queue.emitLog(
            `No target group found for mill: ${itemdata.mill}`,
            'warning'
          );
          continue;
        }

        // Add message to queue
        this.queue.push({
          type: 'send_message',
          queueType: 'grading',
          data: {
            to: targetGroup,
            message: message,
          },
        });

        // Update processed data
        await this.updateDataMill({
          id: id_jobs,
          pdf_name: pdf_name,
          image_name: image_name,
        });
      }

      global.queue.emitLog(
        `Processed ${data.length} mill data entries`,
        'success'
      );
    } catch (error) {
      global.queue.emitLog(
        `Error fetching mill data: ${error.message}`,
        'error'
      );
      throw error;
    }
  }

  async runJobsMill() {
    try {
      const response = await axios.get(`${this.baseUrl}/getdatamill`, {
        params: this.credentials,
      });
      global.queue.emitLog('Successfully fetched mill jobs', 'success');
      return response.data;
    } catch (error) {
      global.queue.emitLog(
        `Error fetching mill jobs: ${error.message}`,
        'error'
      );
      throw error;
    }
  }

  async updateDataMill(data) {
    try {
      await axios.post(`${this.baseUrl}/updatedatamill`, {
        ...this.credentials,
        id: data.id,
        pdf_name: data.pdf_name,
        image_name: data.image_name,
      });
      global.queue.emitLog('Successfully updated mill data', 'success');
    } catch (error) {
      global.queue.emitLog(
        `Error updating mill data: ${error.message}`,
        'error'
      );
      throw error;
    }
  }

  formatGradingMessage(itemdata) {
    let message = `*Berikut Hasil Grading Total ${itemdata.estate} ${itemdata.afdeling}*:\n`;
    message += `*Tanggal*: ${itemdata.Tanggal}\n`;
    message += `*Jam*: ${itemdata.waktu_grading}\n`;
    message += `*Ripeness*: ${itemdata.Ripeness} jjg (${itemdata.percentase_ripenes}%)\n`;
    // ... rest of message formatting ...
    message += `Generated by Digital Architect SRS bot`;
    return message;
  }

  getTargetGroup(mill) {
    const groups = {
      SYM: '6281397270799-1635156024@g.us',
      SGM: '6282257572112-1635223872@g.us',
      SLM: '6281397270799-1565316655@g.us',
      NBM: '6285655573821-1566449850@g.us',
      MLM: '120363332857987276@g.us',
      NKM: '120363046524351245@g.us',
      SCM: '120363332360538214@g.us',
    };
    return groups[mill];
  }
}

module.exports = new GradingMill();
